---
name: Test Build Linux

on:
  push:
    branches:
      - dev
permissions:
  contents: write # Needed to create releases and upload assets

jobs:
  build-linux:
    name: Build Linux executable with PyInstaller
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
        with:
          egress-policy: audit # Monitor outbound connections

      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Fetch all history for version detection

      - name: Ensure Poetry cache directory exists
        run: mkdir -p ~/.cache/pypoetry

      - name: Cache pip
        id: cache-pip
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Print pip cache status
        run: |
          echo "pip cache hit: ${{ steps.cache-pip.outputs.cache-hit }}"

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Print Poetry cache status
        run: |
          echo "poetry cache hit: ${{ steps.cache-poetry.outputs.cache-hit }}"

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          py-installer: true
          upx: true
          install-package: true

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          parent_sha=$(git rev-parse --verify HEAD^ 2>/dev/null || echo "")
          echo "Parent commit SHA: $parent_sha"
          if [ -n "$parent_sha" ]; then
              echo "sha=$parent_sha" >> "$GITHUB_OUTPUT"
          fi

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@b1778166f13188a9d478e2d1198f993011ba9864 # v2.0.3
        with:
          version-command: |
            version=$(poetry version | awk '{print $2}')
            echo "$version"

      - name: Build Linux executable with PyInstaller (NO compression, DEBUG log)
        run: |
          set -e
          if ! command -v pyinstaller &> /dev/null; then
              echo "PyInstaller not found"
              exit 1
          fi

          pyinstaller \
            --clean \
            --console \
            --noconfirm \
            --onedir \
            --log-level DEBUG \
            --name VaMoTelBot \
            --debug all \
            --optimize 2 \
            src/vamo_telbot/main.py

      - name: Upload build artifact (Folder)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: VaMoTelBot # Artifact name
          path: dist/ # Path to collect
          compression-level: 9
          if-no-files-found: error # Fail if nothing is found

      - name: Publish or edit the draft notes
        id: create_draft_release
        uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        with:
          publish: false
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
